coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        paths:
          - "src"
        branches:
          - main

# ignore:
#   - src/pypetal/pyccf/utils.py
